---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[motd_rhel::default]
    attributes:kit